### ISSUE TITLE
Remove pipeline_executions directories

### ISSUE THREAD

**Issue by Dr0p42** [jupyter-naas/data-product-framework#14]
I used this repository as a template just now and deleted the `models/advanced` directory, while doing so I figured that there are a lot of pipeline execution store in this template when I think they should not be there: https://github.com/jupyter-naas/data-product-framework/tree/main/models/advanced/schedulers/pipeline_executions

**Comment by Dr0p42** [comment]
@FlorentLvr what do you think?

**Comment by FlorentLvr** [comment]
> @FlorentLvr what do you think?

Yes, it should not be there. Just deleted them! @Dr0p42
